export default function Terms() {
  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-12 max-w-4xl">
      <header className="mb-12 border-b-2 border-foreground pb-4">
        <h1 className="font-headline text-5xl md:text-6xl font-bold text-foreground tracking-tight uppercase">
          About & Terms
        </h1>
        <p className="font-serif text-lg text-muted-foreground mt-4">
          Information regarding The Walleye Wire's operations and content.
        </p>
      </header>

      <div className="prose prose-lg prose-p:font-serif prose-headings:font-headline prose-a:text-primary max-w-none text-foreground bg-card p-8 border border-border">
        <h2>About The Walleye Wire</h2>
        <p>
          The Walleye Wire is an independent, experimental news aggregator focused on Port Clinton, Ohio and Ottawa County. 
          Our goal is to provide accessible, readable summaries of local happenings, government proceedings, and community events.
        </p>
        <p>
          <strong>This site utilizes artificial intelligence.</strong> Our systems fetch public RSS feeds, scrape publicly available government meeting minutes, and use AI models to summarize and format this information into readable news stories. 
        </p>

        <hr className="my-8 border-border" />

        <h2>Disclaimer of Affiliation</h2>
        <p>
          The Walleye Wire is a private, independent project. <strong>We are NOT affiliated with, endorsed by, or representative of the City of Port Clinton, Ottawa County, or any government entity.</strong>
        </p>
        <p>
          For official government business, notices, and records, please visit the official government websites:
        </p>
        <ul>
          <li><a href="https://www.portclinton.com/" target="_blank" rel="noopener noreferrer">Official City of Port Clinton Website</a></li>
          <li><a href="https://www.co.ottawa.oh.us/" target="_blank" rel="noopener noreferrer">Official Ottawa County Website</a></li>
        </ul>

        <hr className="my-8 border-border" />

        <h2>Content Accuracy & AI Limitations</h2>
        <p>
          Because our stories are generated by AI summarizing raw source documents, there is a possibility of errors, omissions, or misinterpretations (hallucinations). 
        </p>
        <p>
          We provide a "View Source" link on every story. We strongly encourage readers to click through and read the original source material, especially regarding sensitive topics like government resolutions, ordinances, and votes.
        </p>
        <p>
          The Walleye Wire provides this information on an "as-is" basis without warranties of any kind regarding accuracy or completeness.
        </p>
      </div>
    </div>
  );
}
